baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "R for the rest of us"
theme = "hugo-future-imperfect"
googleAnalytics = ""
disqusShortname = "http-kgilds-rbind-io."
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/kgilds"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/kevin_gilds"
[[menu.main]]
   name = "Resume"
   url = "/Resume/"

[params]
    description = "R for the rest of us."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

