baseurl = "http://kgilds.rbind.io/"
relativeurls = true
languageCode = "en-us"
title = "R for the rest of us"
theme = "hugo-future-imperfect-master"
googleAnalytics = "UA-111258922-1"
disqusShortname = "r-for-the-rest-of-us"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"


    
[[menu.main]]
	name = "Resume"
    url = "/Resume/"



[[menu.main]]
    name = "Worknotes"
    	identifier = "Worknotes"
        url = "/notes"

[[menu.main]]
  name = "About"
  url = "/about/"
  identifier = "fa fa-id-card-o"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  identifier = "fa fa-newspaper-o"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  identifier = "fa fa-list"
  weight = 4

[params]
    description = "R for the rest of us."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    socialAppearAtTop    = true
    socialAppearAtBottom = true

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

[params.intro]
    header    = "Learning R for Social Good"

    paragraph = "Nonprofit Sector Data Science"

    about     = "Documenting my efforts to learn R and life."



    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
    [params.intro.pic]
    src       = "img/batman.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = true
    width     = ""
    alt       = "Hugo Future Imperfect"


# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "kgilds"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "kevingilds"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "kevin_gilds"
    email           = ""

